// <auto-generated />
using System;
using CalendarBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251202125100_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("CalendarBackend.Model.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("CalendarBackend.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 2,
                            Description = "Long daily standup description so i can test how it would look if the description of this event is long.",
                            EndDate = new DateTime(2025, 10, 3, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            OrganizerId = 1,
                            RoomId = 9,
                            StartDate = new DateTime(2025, 10, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Daily standup"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Call with product owner",
                            EndDate = new DateTime(2025, 10, 3, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            OrganizerId = 1,
                            RoomId = 8,
                            StartDate = new DateTime(2025, 10, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "P.O. meeting"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Call with product owner",
                            EndDate = new DateTime(2025, 10, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            OrganizerId = 1,
                            RoomId = 8,
                            StartDate = new DateTime(2025, 10, 3, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "P.O. meeting part 2"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Call with product owner",
                            EndDate = new DateTime(2025, 10, 3, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            OrganizerId = 1,
                            RoomId = 8,
                            StartDate = new DateTime(2025, 10, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "P.O. meeting part 3"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Daily standup description",
                            EndDate = new DateTime(2025, 10, 4, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            OrganizerId = 1,
                            RoomId = 9,
                            StartDate = new DateTime(2025, 10, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Daily standup"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lunch in canteen",
                            EndDate = new DateTime(2025, 10, 4, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            OrganizerId = 1,
                            RoomId = 0,
                            StartDate = new DateTime(2025, 10, 4, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lunch"
                        });
                });

            modelBuilder.Entity("CalendarBackend.Model.EventAttendees", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId", "UserId");

                    b.ToTable("EventAttendees");

                    b.HasData(
                        new
                        {
                            EventId = 4,
                            UserId = 0
                        },
                        new
                        {
                            EventId = 4,
                            UserId = 1
                        },
                        new
                        {
                            EventId = 4,
                            UserId = 2
                        },
                        new
                        {
                            EventId = 5,
                            UserId = 0
                        },
                        new
                        {
                            EventId = 5,
                            UserId = 1
                        },
                        new
                        {
                            EventId = 5,
                            UserId = 2
                        },
                        new
                        {
                            EventId = 1,
                            UserId = 3
                        },
                        new
                        {
                            EventId = 1,
                            UserId = 4
                        },
                        new
                        {
                            EventId = 1,
                            UserId = 5
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 3
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 4
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 5
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 3
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 4
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("CalendarBackend.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeY")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("CalendarBackend.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("BLOB");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "biography",
                            Email = "John@gmail.com",
                            Name = "John",
                            Password = "password",
                            Role = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
