// <auto-generated />
using System;
using CalendarBackend.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MyBackend.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260202133049_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("CalendarBackend.Model.Attendance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("RoomId");

                    b.HasIndex("UserId");

                    b.ToTable("Attendances");
                });

            modelBuilder.Entity("CalendarBackend.Model.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsOpen")
                        .HasColumnType("INTEGER");

                    b.Property<int>("OrganizerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RoomId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("RoomId1")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerId");

                    b.HasIndex("RoomId");

                    b.HasIndex("RoomId1");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Long daily standup description so i can test how it would look if the description of this event is long.",
                            EndDate = new DateTime(2025, 10, 5, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            OrganizerId = 1,
                            RoomId = 10,
                            StartDate = new DateTime(2025, 10, 5, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Daily standup"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Long daily standup description so i can test how it would look if the description of this event is long.",
                            EndDate = new DateTime(2025, 10, 3, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            OrganizerId = 1,
                            RoomId = 10,
                            StartDate = new DateTime(2025, 10, 3, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Daily standup"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Call with product owner",
                            EndDate = new DateTime(2025, 10, 3, 15, 45, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            OrganizerId = 1,
                            RoomId = 9,
                            StartDate = new DateTime(2025, 10, 3, 15, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "P.O. meeting"
                        },
                        new
                        {
                            Id = 4,
                            Description = "Call with product owner",
                            EndDate = new DateTime(2025, 10, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            OrganizerId = 1,
                            RoomId = 9,
                            StartDate = new DateTime(2025, 10, 3, 15, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "P.O. meeting part 2"
                        },
                        new
                        {
                            Id = 5,
                            Description = "Call with product owner",
                            EndDate = new DateTime(2025, 10, 3, 17, 30, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            OrganizerId = 1,
                            RoomId = 9,
                            StartDate = new DateTime(2025, 10, 3, 16, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "P.O. meeting part 3"
                        },
                        new
                        {
                            Id = 6,
                            Description = "Daily standup description",
                            EndDate = new DateTime(2025, 10, 4, 11, 30, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = false,
                            OrganizerId = 1,
                            RoomId = 10,
                            StartDate = new DateTime(2025, 10, 4, 11, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Daily standup"
                        },
                        new
                        {
                            Id = 7,
                            Description = "Lunch in canteen",
                            EndDate = new DateTime(2025, 10, 4, 13, 15, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            OrganizerId = 1,
                            RoomId = 1,
                            StartDate = new DateTime(2025, 10, 4, 12, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Lunch"
                        },
                        new
                        {
                            Id = 8,
                            Description = "",
                            EndDate = new DateTime(2025, 10, 3, 20, 30, 0, 0, DateTimeKind.Unspecified),
                            IsOpen = true,
                            OrganizerId = 1,
                            RoomId = 9,
                            StartDate = new DateTime(2025, 10, 3, 19, 30, 0, 0, DateTimeKind.Unspecified),
                            Title = "Ping pong"
                        });
                });

            modelBuilder.Entity("CalendarBackend.Model.EventAttendees", b =>
                {
                    b.Property<int>("EventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AcceptedInvite")
                        .HasColumnType("INTEGER");

                    b.HasKey("EventId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("EventAttendees");

                    b.HasData(
                        new
                        {
                            EventId = 4,
                            UserId = 3,
                            AcceptedInvite = false
                        },
                        new
                        {
                            EventId = 4,
                            UserId = 1,
                            AcceptedInvite = false
                        },
                        new
                        {
                            EventId = 4,
                            UserId = 2,
                            AcceptedInvite = false
                        },
                        new
                        {
                            EventId = 5,
                            UserId = 3,
                            AcceptedInvite = false
                        },
                        new
                        {
                            EventId = 5,
                            UserId = 1,
                            AcceptedInvite = false
                        },
                        new
                        {
                            EventId = 5,
                            UserId = 2,
                            AcceptedInvite = false
                        },
                        new
                        {
                            EventId = 1,
                            UserId = 3,
                            AcceptedInvite = false
                        },
                        new
                        {
                            EventId = 1,
                            UserId = 2,
                            AcceptedInvite = false
                        },
                        new
                        {
                            EventId = 1,
                            UserId = 1,
                            AcceptedInvite = false
                        },
                        new
                        {
                            EventId = 2,
                            UserId = 1,
                            AcceptedInvite = false
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 3,
                            AcceptedInvite = false
                        },
                        new
                        {
                            EventId = 3,
                            UserId = 1,
                            AcceptedInvite = false
                        });
                });

            modelBuilder.Entity("CalendarBackend.Model.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Capacity")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PositionX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PositionY")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeX")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SizeY")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Rooms");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Capacity = 10,
                            Name = "Canteen",
                            PositionX = 65,
                            PositionY = 10,
                            SizeX = 25,
                            SizeY = 25
                        },
                        new
                        {
                            Id = 2,
                            Capacity = 10,
                            Name = "Entrance Hall",
                            PositionX = 35,
                            PositionY = 10,
                            SizeX = 30,
                            SizeY = 40
                        },
                        new
                        {
                            Id = 3,
                            Capacity = 10,
                            Name = "Kitchen",
                            PositionX = 65,
                            PositionY = 35,
                            SizeX = 25,
                            SizeY = 15
                        },
                        new
                        {
                            Id = 4,
                            Capacity = 10,
                            Name = "Room 001",
                            PositionX = 15,
                            PositionY = 10,
                            SizeX = 20,
                            SizeY = 10
                        },
                        new
                        {
                            Id = 5,
                            Capacity = 10,
                            Name = "Room 002",
                            PositionX = 15,
                            PositionY = 20,
                            SizeX = 5,
                            SizeY = 35
                        },
                        new
                        {
                            Id = 6,
                            Capacity = 10,
                            Name = "Room 003",
                            PositionX = 25,
                            PositionY = 25,
                            SizeX = 10,
                            SizeY = 25
                        },
                        new
                        {
                            Id = 7,
                            Capacity = 10,
                            Name = "Room 004",
                            PositionX = 15,
                            PositionY = 55,
                            SizeX = 25,
                            SizeY = 10
                        },
                        new
                        {
                            Id = 8,
                            Capacity = 10,
                            Name = "Room 005",
                            PositionX = 45,
                            PositionY = 55,
                            SizeX = 30,
                            SizeY = 10
                        },
                        new
                        {
                            Id = 9,
                            Capacity = 10,
                            Name = "Room 006",
                            PositionX = 75,
                            PositionY = 50,
                            SizeX = 15,
                            SizeY = 15
                        },
                        new
                        {
                            Id = 10,
                            Capacity = 10,
                            Name = "Room 007",
                            PositionX = 25,
                            PositionY = 65,
                            SizeX = 15,
                            SizeY = 10
                        },
                        new
                        {
                            Id = 11,
                            Capacity = 10,
                            Name = "Room 008",
                            PositionX = 45,
                            PositionY = 65,
                            SizeX = 15,
                            SizeY = 10
                        },
                        new
                        {
                            Id = 12,
                            Capacity = 10,
                            Name = "Room 009",
                            PositionX = 25,
                            PositionY = 75,
                            SizeX = 35,
                            SizeY = 10
                        });
                });

            modelBuilder.Entity("CalendarBackend.Model.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Biography")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("ProfilePicture")
                        .HasColumnType("BLOB");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Biography = "biography",
                            Email = "John@gmail.com",
                            Name = "John",
                            Password = "password",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            Biography = "biography",
                            Email = "Kees@gmail.com",
                            Name = "Kees",
                            Password = "password",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            Biography = "biography",
                            Email = "Jan@gmail.com",
                            Name = "Jan",
                            Password = "password",
                            Role = 0
                        });
                });

            modelBuilder.Entity("CalendarBackend.Model.Attendance", b =>
                {
                    b.HasOne("CalendarBackend.Model.Room", "Room")
                        .WithMany("Attendances")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalendarBackend.Model.User", "User")
                        .WithMany("Attendances")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Room");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalendarBackend.Model.Event", b =>
                {
                    b.HasOne("CalendarBackend.Model.User", "Organizer")
                        .WithMany("OrganizedEvents")
                        .HasForeignKey("OrganizerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalendarBackend.Model.Room", "Room")
                        .WithMany()
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalendarBackend.Model.Room", null)
                        .WithMany("Events")
                        .HasForeignKey("RoomId1");

                    b.Navigation("Organizer");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("CalendarBackend.Model.EventAttendees", b =>
                {
                    b.HasOne("CalendarBackend.Model.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CalendarBackend.Model.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CalendarBackend.Model.Room", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("Events");
                });

            modelBuilder.Entity("CalendarBackend.Model.User", b =>
                {
                    b.Navigation("Attendances");

                    b.Navigation("OrganizedEvents");
                });
#pragma warning restore 612, 618
        }
    }
}
